# Generated by Django 3.1.5 on 2021-01-30 07:25

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='city',
            field=models.CharField(default='Pune', max_length=255),
        ),
        migrations.AddField(
            model_name='books',
            name='condition',
            field=models.CharField(default='Used', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='image1',
            field=models.ImageField(default='Hello', upload_to='books/images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='image2',
            field=models.ImageField(blank=True, upload_to='books/images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='image3',
            field=models.ImageField(blank=True, upload_to='books/images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='image4',
            field=models.ImageField(blank=True, upload_to='books/images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='Pune', max_length=63),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
