# Generated by Django 3.1.5 on 2021-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20210130_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='academic',
            field=models.CharField(choices=[('academic', 'academic'), ('non-academic', 'non-academic')], default='academic', max_length=13),
        ),
    ]
