# Generated by Django 3.1.5 on 2021-01-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_books_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='academic',
            new_name='book_type',
        ),
    ]
