# Generated by Django 3.1.5 on 2021-01-31 20:39

from django.db import migrations, models
import trade.models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20210201_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image1',
            field=models.ImageField(default='books/default.jpg', upload_to=trade.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='books',
            name='image2',
            field=models.ImageField(blank=True, upload_to=trade.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='books',
            name='image3',
            field=models.ImageField(blank=True, upload_to=trade.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='books',
            name='image4',
            field=models.ImageField(blank=True, upload_to=trade.models.user_directory_path),
        ),
    ]
